# Generated by Django 2.2.1 on 2020-04-30 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PropelRapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill_plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billplan', models.CharField(max_length=100)),
                ('billplan_cd', models.CharField(max_length=10)),
                ('is_deleted', models.CharField(choices=[('N', 'NO'), ('Y', 'YES')], default='N', max_length=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=20)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Bill_plan',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cust_org',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_org', models.CharField(max_length=100)),
                ('cust_org_acro', models.CharField(max_length=10)),
                ('onboard_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended')], default='Active', max_length=10)),
                ('is_deleted', models.CharField(choices=[('N', 'NO'), ('Y', 'YES')], default='N', max_length=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=20)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.CharField(max_length=20)),
                ('bill_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PropelRapp.Bill_plan')),
            ],
            options={
                'db_table': 'Cust_org',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.RenameField(
            model_name='camera',
            old_name='username',
            new_name='camname',
        ),
        migrations.RenameField(
            model_name='cluster',
            old_name='name',
            new_name='cluster_name',
        ),
        migrations.RenameField(
            model_name='cluster',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='cluster',
            old_name='modified_at',
            new_name='modified_on',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='IPAddress',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='cameraID',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='modified_date',
        ),
        migrations.AddField(
            model_name='camera',
            name='algo_type',
            field=models.CharField(default='Type', max_length=80),
        ),
        migrations.AddField(
            model_name='camera',
            name='camip',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='camera',
            name='x1_cord',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='camera',
            name='x2_cord',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='camera',
            name='y1_cord',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='camera',
            name='y2_cord',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cluster',
            name='created_by',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='cluster',
            name='modified_by',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='camera',
            name='purpose',
            field=models.CharField(choices=[('Vehicle', 'Vehicle'), ('Person', 'Person')], default='Select Choice', max_length=10),
        ),
    ]
