# Generated by Django 2.2.1 on 2020-05-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PropelRapp', '0002_auto_20200430_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='is_deleted',
            field=models.CharField(choices=[('N', 'NO'), ('Y', 'YES')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='cluster',
            name='is_deleted',
            field=models.CharField(choices=[('N', 'NO'), ('Y', 'YES')], default='N', max_length=1),
        ),
    ]
