# Generated by Django 2.2.1 on 2020-05-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PropelRapp', '0009_auto_20200506_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_deleted',
            field=models.CharField(choices=[('N', 'NO'), ('Y', 'YES')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='role',
            name='is_deleted',
            field=models.CharField(choices=[('N', 'NO'), ('Y', 'YES')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='submenu',
            name='is_deleted',
            field=models.CharField(choices=[('N', 'NO'), ('Y', 'YES')], default='N', max_length=1),
        ),
    ]
