# Generated by Django 2.2.1 on 2020-05-11 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PropelRapp', '0010_auto_20200507_0705'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoleDetails',
            new_name='Roledetail',
        ),
        migrations.AlterModelTable(
            name='roledetail',
            table='Roledetail',
        ),
    ]
