# Generated by Django 2.2.1 on 2020-05-12 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PropelRapp', '0018_auto_20200512_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roledetail',
            name='submenu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PropelRapp.Submenu'),
        ),
        migrations.DeleteModel(
            name='AppUser',
        ),
    ]
