# Generated by Django 2.2.1 on 2020-06-08 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PropelRapp', '0038_auto_20200608_0623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='customer',
        ),
        migrations.AlterField(
            model_name='roledetail',
            name='submenu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PropelRapp.Submenu'),
        ),
    ]
